# Generated by Django 6.0.2 on 2026-02-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon raqam'),
        ),
    ]
