# Generated by Django 6.0.2 on 2026-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_users', '0002_usermod_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='is_email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
