# Generated by Django 6.0.2 on 2026-02-20 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bun_core', '0006_sale_products_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='soni')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='qoshilgan vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bun_core.products', verbose_name='products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='carts')),
            ],
            options={
                'verbose_name': 'savatcha',
                'verbose_name_plural': 'savatchalar',
            },
        ),
    ]
