# Generated by Django 6.0.2 on 2026-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsmodel',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
