# Generated by Django 6.0.2 on 2026-02-21 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0009_remove_products_sales_products_sales'),
        ('carts', '0002_cartsmodel_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsmodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qoshilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='cartsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bun_core.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartsmodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='cartsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterModelTable(
            name='cartsmodel',
            table='savat',
        ),
    ]
