# Generated by Django 6.0.2 on 2026-02-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0010_alter_products_options'),
        ('carts', '0004_alter_cartsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='bun_core.products', verbose_name='Product'),
        ),
    ]
