# Generated by Django 5.2.10 on 2026-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bunbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='haqida')),
                ('create_ad', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='rasm')),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'bun base',
                'verbose_name_plural': 'bun base',
                'db_table': 'bunbase',
            },
        ),
    ]
