# Generated by Django 5.2.10 on 2026-01-18 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0003_products_image_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Vaqt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updt_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
