# Generated by Django 6.0.2 on 2026-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0004_products_created_time_products_updt_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Narx'),
        ),
    ]
