# Generated by Django 6.0.2 on 2026-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0006_sale_products_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Skidka ishlasinmi?'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='end_date',
            field=models.DateTimeField(verbose_name='Qachon tugashi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Skidka nomi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Skida foizda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_date',
            field=models.DateTimeField(verbose_name='Qachon boshlanishi'),
        ),
    ]
