# Generated by Django 6.0.2 on 2026-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0007_alter_sale_active_alter_sale_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Skida foizda'),
        ),
    ]
