# Generated by Django 6.0.2 on 2026-02-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0008_alter_sale_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sales',
        ),
        migrations.AddField(
            model_name='products',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='bun_core.sale', verbose_name='Skidka'),
        ),
    ]
