# Generated by Django 6.0.2 on 2026-02-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0009_remove_products_sales_products_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'product', 'verbose_name_plural': 'productlar'},
        ),
    ]
