# Generated by Django 6.0.2 on 2026-02-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bun_core', '0010_alter_products_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon')),
                ('address', models.CharField(max_length=100, verbose_name='Manzil')),
                ('card_number', models.CharField(max_length=19, verbose_name='Karta raqami')),
                ('card_expiry', models.CharField(max_length=5, verbose_name='Amal qilish muddati')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bun_core.products')),
            ],
            options={
                'verbose_name': 'Sotilgan Zakaz',
                'verbose_name_plural': 'Sotilgan Zakazlar',
                'db_table': 'order_item',
            },
        ),
    ]
